### ISSUE TITLE
ImportError: cannot import name 'LMSKerasCallback'

### ISSUE THREAD

**Issue by ticlazau** [IBM/tensorflow-large-model-support#16]
Hi Sam,

I am using WML-CE 1.6.1 (TF 1.14) with a provided synthetic example: Keras_ResNet50.py

$python Keras_ResNet50.py --image_size 2300 
2019-06-24 04:10:47.551637: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
WARNING: Logging before flag parsing goes to stderr.
W0624 04:10:49.657887 140735954111392 deprecation_wrapper.py:119] From /home/coredump/anaconda3/envs/powerai-1.6.1/lib/python3.6/site-packages/tflms-2.0.1-py3.6.egg/tensorflow_large_model_support/lms.py:25: The name tf.train.SessionRunHook is deprecated. Please use tf.estimator.SessionRunHook instead.

Traceback (most recent call last):
  File "Keras_ResNet50.py", line 60, in <module>
    from tensorflow_large_model_support import LMSKerasCallback
ImportError: cannot import name 'LMSKerasCallback'

Any advice?

**Comment by smatzek** [comment]
It appears you are attempting to use the Keras_ResNet50.py example from this github repository with WML CE 1.6.1. As noted in this repository's readme, the Large Model Support in PowerAI (and WML CE) is newer implementation. WML CE's new implementation is not API compatible with the version in this  repository.

The PowerAI / WML CE documentation points at the https://github.com/IBM/powerai/ repository for its examples.  The repository has branches for the different PowerAI/WML CE releases. The TFLMSv2 (new implementation examples) for WML CE 1.6.1 are here: https://github.com/IBM/powerai/tree/wmlce-1.6.1/examples/tensorflow_large_model_support/v2
