### ISSUE TITLE
tf-lms for tensorflow v2?

### ISSUE THREAD

**Issue by vmiheer** [IBM/tensorflow-large-model-support#19]
Hello seems like current version of tf-lms supports only tensorflow v1?
```ipython
In [1]: from tensorflow_large_model_support import LMSKerasCallback
   ...: # LMSKerasCallback and LMS share a set of keyword arguments. Here we just
   ...: # use the default options.
   ...: lms_callback = LMSKerasCallback()
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f419b421d3ca> in <module>
----> 1 from tensorflow_large_model_support import LMSKerasCallback
      2 # LMSKerasCallback and LMS share a set of keyword arguments. Here we just
      3 # use the default options.
      4 lms_callback = LMSKerasCallback()

~/miniconda3/envs/tflms/lib/python3.7/site-packages/tensorflow_large_model_support/__init__.py in <module>
     14 # ==============================================================================
     15
---> 16 from tensorflow_large_model_support.lms import LMS
     17 from tensorflow_large_model_support.lms import LMSSessionRunHook
     18 from tensorflow_large_model_support.lms import LMSKerasCallback

~/miniconda3/envs/tflms/lib/python3.7/site-packages/tensorflow_large_model_support/lms.py in <module>
     16 """
     17 import tensorflow as tf
---> 18 import tensorflow.contrib.graph_editor as ge
     19 from tensorflow.contrib.graph_editor import util
     20

ModuleNotFoundError: No module named 'tensorflow.contrib'
```
Possibly because of:
```
In [5]: tf.version.VERSION
Out[5]: '2.0.0'
```

**Comment by smatzek** [comment]
You are correct. This version of TFLMS does not support TensorFlow v2. There are at least two issues: 1. its dependence on contrib, 2. its use of Sessions, graphs, and many other things that are V1.

I have tested the latest version of TFLMSv2 in Watson Machine Learning Community Edition (WMLCE) with TensorFlow v2 while running it in v1 compat mode. This version of TFLMS does not have dependencies on the contrib directory and does work when running TensorFlow v2 in non-eager / graph-mode.

I would suggest giving that a try for TensorFlow 2.0 even though that usage is not officially supported from WMLCE.

The TFLMSv2 conda package can be installed from the WMLCE conda channel here: https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/#/

**Comment by mpetroff** [comment]
@smatzek What's the license for the TFLMSv2 Conda package?

While this repository is Apache-licensed, the Conda package contains no licensing information, only saying `Licensed Materials - Property of IBM` in the Python files (which isn't a license). I can't find any clear licensing information in any of the WMLCE documentation either.

**Comment by smatzek** [comment]
The TFLMSv2 conda package in IBM Watson Machine Learning Community Edition is not open source, per the header. The license it falls under is the IBM Watson Machine Learning Community Edition license which should be displayed during the conda installation of tensorflow-large-model-support and must be accepted for the install and use of the product. Post installation the various translations of the license displayed are stored here `~/.powerai/powerai-license/1.6.2/license/`.

TFLMSv2 is also protected by patent law as some of its functionality has been submitted in a patent application to the US Patent Office.

While TFLMSv2 is currently closed source, we do intend to open source it under the Apache 2.0 license and put its code in this git repository. However, that re-licensing hasn't happened yet.

**Comment by smatzek** [comment]
A new implementation of TensorFlow Large Model Support for TensorFlow 2 has been released. This implementation does not require tuning and is easier to enable in your code. Please see the current master branch version of the README.md for more information.
@vmiheer FYI

@mpetroff This new version is open source under Apache 2 and the code is included in the patches directory of the master branch of this repo.

**Comment by smatzek** [comment]
@mpetroff The TFLMSv2 source is now open source under the Apache 2.0 license and resides in the tflmsv2 branch of this repository here: https://github.com/IBM/tensorflow-large-model-support/tree/tflmsv2
