### ISSUE TITLE
LMS does not turn on even my training model broke down because of out of memory

### ISSUE THREAD

**Issue by Jingnan-Jia** [IBM/tensorflow-large-model-support#22]
I train a 3D U-Net model with batch_size=1 and input size=256*256*256. I use ubuntu 18 and RTX 6000 with 24 GB GPU RAM.
```
lms_cb = LMS()
lms_cb.batch_size = 1
os.environ['TF_LMS_SIMULATOR_MEM_RATIO'] = '0.4'  # bigger than 0.8 may tricger error OOM
lms_cb.sync_mode=3
lms_cb.autotune_plot = True
history = net.fit(x, y, batch_size=batch_sz, validation_data=valid_data, callbacks=[lms_cb, checker, saver, csv_logger])
```
but it shown that LMS is not necessary.

```Created TensorFlow device (/device:GPU:0 with 22722 MB memory) -> physical GPU (device: 0, name: Quadro RTX 6000, pci bus id: 0000:3b:00.0, compute capability: 7.5)
I0101 19:37:24.588294 139849692407616 lms.py:1275] [LMS][0] [Simulator] Available memory for simulation: 8.79 GiB (memory ratio: 0.4)
I0101 19:37:24.588538 139849692407616 lms.py:1275] [LMS][0] [Simulator] Available CPU memory for simulation: 64.0 GiB
I0101 19:37:24.589878 139849692407616 lms.py:1275] [LMS][0] [Simulator] Batch size used for simulation: 1
I0101 19:37:25.994517 139849692407616 lms.py:1275] [LMS][0] [Simulator] Found a parameter set: swapout_threshold 1558, swapin_ahead 1, swapin_groupby 0, sync_mode 0
I0101 19:37:25.996134 139849692407616 lms.py:1275] [LMS][0] LMS is not necessary. Turned LMS off.
I0101 19:37:26.055914 139849692407616 lms.py:1275] [LMS][0] Editing model for LMS
I0101 19:37:26.644204 139849692407616 lms.py:1275] [LMS][0] The graph has 30991 vertices and 37521 edges.
I0101 19:37:26.644354 139849692407616 lms.py:1275] [LMS][0] The graph has 225.41 MiB of learning parameters.
I0101 19:37:26.644531 139849692407616 lms.py:1275] [LMS][0] The largest GPU operation is conv3d_13/kernel/Initializer/random_uniform/mul consuming 0.01 GiB
I0101 19:37:33.928616 139849692407616 lms.py:1275] [LMS][0] Original categorized topological sort has 1558 levels.
I0101 19:37:34.083726 139849692407616 lms.py:1275] [LMS][0] LMS is not necessary. Turned LMS off.```

After that OOM errors occured.

**Comment by smatzek** [comment]
I posted this on #6 as well:
```
TFLMSv2 (in WMLCE and PowerAI 1.6.0) uses an auto-tuning simulator to attempt to find the optimized tuning values. This simulator depends on accurately calculating your model tensor sizes. It uses static graph analysis to do this and therefore cannot account for some overhead that some of the operations used by your model may trigger. In addition, we have seen some models where the tensor size calculations are done by the simulator do not work well and it then leads to cases like yours, where the auto-tuning determines that no LMS swapping nodes are required, when in fact they are.

In these cases you can sometimes force the auto-tuning to work by setting mem ratio lower as you did, when that doesn't yield results you need to follow the manual tuning instructions in the WML CE documentation and not rely on automatic tuning.
```

In terms of your code and output above, I see that it is saying your largest op is only 0.01 GB. That is very small and makes me think your model is also not working well with the auto tuner.

Your code snippet has an error, but it likely will not affect the outcome of the auto-tuning not working:
```
lms_cb = LMS()
lms_cb.sync_mode=3 ### This is not the correct way to set sync_mode. sync_mode is a parameter to the LMS constructor
```

I suggest you try following the manual tuning instructions in the WMLCE documentation.
You could start with:
```
lms_cb = LMS(swapout_threshold=1, swapin_ahead=1, swapin_groupby=0)
history = net.fit(x, y, batch_size=batch_sz, validation_data=valid_data, callbacks=[lms_cb, checker, saver, csv_logger])
```
The maximum values for those 3 keyword arguments to LMS with your model are 1558, from this output line `Original categorized topological sort has 1558 levels.`

**Comment by smatzek** [comment]
I also use a 3D U-Net for a lot of TFLMS testing and the model is here: https://github.com/smatzek/3DUnetCNN/

A lot of paper publishes, performance results, and blogs use this model with TFLMS and are linked from here:
https://developer.ibm.com/linuxonpower/2019/06/11/tensorflow-large-model-support-resources/

**Comment by Jingnan-Jia** [comment]
Thank you. I will try your advice. By the way, I wonder if it is because of my model. My model for multi task segmentation is composed with 2 3D U-Nets with a shared encoder:
```
shared_encoder = ...
decoder_1 = ...
decoder_2 = ...
model_1 = Model(shared_encoder, decoder_1)
model_2 = Model(shared_encoder, decoder_2)
model_1.compile()
model_2.compile()
for i in range(100):
    model_1.fit(x_1,y_1, callback=[lms_callbacks])
    model_2.fit(x_2,y_2, callback=[lms_callbacks])
```
The two models is compiled and trained seperately but with a shared encoder.

I want to know if it is the special design of my whole model that cause some unexpected errors? Or the model design has no effect?

**Comment by Jingnan-Jia** [comment]
Another question is: if tflms is compatible with mix precision? ([mixed precision](https://developer.nvidia.com/automatic-mixed-precision) is another technique which can reduce the GPU memory by store feature maps with 16 bits instead of 32 bits. )

**Comment by smatzek** [comment]
While I have not tested it, it should work with mixed precision. TFLMS will insert swapping nodes before in the graph in the python layer before the mixed precision graph optimizer which is written in native code has a chance to run. This will probably make auto-tuning over estimate the amount of swapping needed if precision is selectively changed to FP16. However, in general the swapping nodes added by TFLMS should still function despite mix precision doing additional changes afterward.

**Comment by smatzek** [comment]
The poor functioning of auto-tuning on your model(s) maybe due to the way you are training, but I wouldn't want to say for sure that is the case.

**Comment by smatzek** [comment]
A new implementation of TensorFlow Large Model Support has been released. This implementation does not require tuning and is easier to enable in your code. Please see the current master branch version of the README.md for more information.
