### ISSUE TITLE
Tensorflow 2 eager mode support

### ISSUE THREAD

**Issue by anji993** [IBM/tensorflow-large-model-support#45]
Hello, can LMS works in the eager model in tensorflow 2?

And, is there a plan to release patches for higher tensorflow versions than 2.1?

**Comment by jayfurmanek** [comment]
Hi,
Yes. In TensorFlow 2 we moved the LMS function from the Python layer (where it relied on the pre-built graph existing) to the core memory manager.
The Tensorflow 2.1 package from IBM's WML CE (https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/) includes LMS built in and this will work with eager mode (which is enabled by default in TF2).

The answer to you second question is unfortunately no for now.

**Comment by jayfurmanek** [comment]
Oh, I failed to mention that there is a 2.2 build enabled with LMS in the "Early Access" WML CE channel:

https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/

That was the last update we did. I'll investigate about pushing the patch set out for that build.

**Comment by smatzek** [comment]
In addition, we just merged a PR in this repository which adds the TensorFlow 2.2.0 patch to the patches directory, updates the examples, readme, and allocator stats documentation.

No work has been done for LMS on versions later than 2.2.0 and as @jayfurmanek said there are unfortunately no current plans to do so.

**Comment by gh-lgs** [comment]
I am not sure how or why I am added to this email thread but please take me 
off. I cannot seem to unsubscribe the link does not work.









 Robert Stemmerich

Robert Stemmerich

office:248-655-2700 ex1711

desk:248-655-2546

cell:248-709-2571

The information contained in this e-mail is confidential and for the 
intended recipient only, if you are not the intended recipient, delete this 
correspondence.
