### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.config.experimental' has no attribute 'set_lms_enabled'

### ISSUE THREAD

**Issue by GF-Huang** [IBM/tensorflow-large-model-support#49]
![image](https://user-images.githubusercontent.com/4510984/101808540-6d797c00-3b51-11eb-8fad-0c0a93da9d26.png)

![image](https://user-images.githubusercontent.com/4510984/101808561-736f5d00-3b51-11eb-8e76-898b15b16050.png)

**Comment by smatzek** [comment]
`tensorflow-base` needs to come from public.dhe.ibm.com as well. You may need to use strict channel priority. See the "Helping the conda installer: strict channel priority and the powerai-release package" section here: https://www.ibm.com/support/knowledgecenter/SS5SF7_1.7.0/navigation/wmlce_install.htm

**Comment by GF-Huang** [comment]
@smatzek Thanks your guide. By the way, which version of `cudatoolkit` and `cudnn` should I install for TFLMS? 

I got `InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version` now.

![image](https://user-images.githubusercontent.com/4510984/101818932-88eb8380-3b5f-11eb-8b60-e3e9bd703756.png)

**Comment by jayfurmanek** [comment]
You need to have a new driver. WML-CE uses CUDA 10.2, so you should have a driver compatible with that version (CUDA itself is installed as a conda package)

**Comment by GF-Huang** [comment]
So I need to install a new driver only or driver include cudatoolkit? 

This is really a headache, I can not understand Cudatoolkit and Cuda Driver and Cuda itself in the end what is the relationship between and the difference.

**Comment by jayfurmanek** [comment]
You need just the driver. Although if you install the entire cuda toolkit, the driver will be installed as well.

For you understanding:
There are a few different pieces that are need for the GPUs to work:
The "driver" which includes:
   - a kernel module
   - a usespace component (libcuda.so)
And "cuda" (or "cuda toolkit") that includes many shared libraries, the nvcc compiler and other utilities
   - this piece is pure userspace and can be located anywhere, although when installed locally is at `/usr/local/cuda`

When using WML CE (or even just bare Anaconda), the cuda piece is provided by a conda package. This package contains all the components from the cuda toolkit that are needed at runtime (it doesn't include the nvcc compilers - WML CE provides those in a package called `cudatoolkit-dev`)

The driver can be downloaded and installed separately, or along with the complete cudatoolkit:
https://www.nvidia.com/Download/index.aspx

New drivers generally work with a certain version of CUDA, or older. So keeping the driver up to date is always a good idea.
