### ISSUE TITLE
Why should H2D_stream_ wait for compute_stream_ in "PageinAsync"?

### ISSUE THREAD

**Issue by haiqwa** [IBM/tensorflow-large-model-support#55]
I notice that `H2D_stream_` must wait for `cmopute_stream` in the implementation of `PageinAsync`([link](https://github.com/IBM/tensorflow-large-model-support/blob/master/patches/tensorflow_v2.1.0_large_model_support.patch#L934)).

And I'm very confused about it. From the comment([link](https://github.com/IBM/tensorflow-large-model-support/blob/master/patches/tensorflow_v2.1.0_large_model_support.patch#L933)), it suggests that the device buffer is only available after computation completes. However, I think memory allocation is not conflict with computation. So, I'm curious about the necessity of the synchronization.

It would be appreciated to get reply.

**Comment by smatzek** [comment]
That synchronization the functional issues caused by performing LMS transfers prematurely. We must synchronize with the compute stream before paging data out or paging back in to potentially-repurposed device buffers.
