### ISSUE TITLE
nvprof seems to not be working/logging for ManyModels.py

### ISSUE THREAD

**Issue by cgreen18** [IBM/tensorflow-large-model-support#58]
Simply, I cannot find the output for nvprof when running ManyModels.py. I am adding the "--nvprof" command line argument when it runs but I cannot find where the output is going. nvprof documentation says that it should be in stderr but that doesn't seem to work. Am I missing something? Thank you.

It is correctly starting and stopping because it prints "Starting [/Stopping] cuda profiler" at the correct batches of the correct epoch.

**Comment by smatzek** [comment]
ManyModels.py assumes you are running nvprof as a separate monitoring process like this: `nvprof --devices 0 --track-memory-allocations on --profile-api-trace none --openacc-profiling off -o outputfile%p.nvvp --profile-all-processes --profile-from-start off`. The `-o` parameter in that command gives the output file template name.
